name              'osl-ortsoc'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-ortsoc'
issues_url        'https://github.com/osuosl-cookbooks/osl-ortsoc/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-ortsoc'
chef_version      '>= 17.0'
version           '0.1.0'

supports          'almalinux', '~> 9.0'
